version: '3'

services:
  # api:
  #   env_file:
  #     - .env
  #   build:
  #     context: "./"
  #   ports:
  #     - "3000:3000"
  #   container_name: node-api
  #   volumes:
  #     - .:/app
  #   links:
  #     - mongo
  #   networks:
  #     - mongo-compose-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: modal
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # - ./data:/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge